# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
