# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='message',
            name='video_id',
            field=models.TextField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.TextField(max_length=50),
        ),
    ]
