# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180804_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
