# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180806_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageId',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
